SELECT V.CUSTOMER_ID,	
	V.ORDER_PURCHASE_TIMESTAMP,
	P.PRODUCT_CATEGORY_NAME,
	IP.PRICE
	FROM VENDAS V	
	INNER JOIN ITENSPEDIDOS IP ON V.ORDER_ID = IP.ORDER_ID
	INNER JOIN PRODUTOS P ON IP.PRODUCT_ID = P.PRODUCT_ID	
	WHERE V.ORDER_STATUS = 'delivered'
	ORDER BY P.PRODUCT_CATEGORY_NAME DESC
